server:
  address: 0.0.0.0
java:
  net:
    preferIPv4Stack: true

spring:
  main:
    web-application-type: servlet
  application:
    name: user-service
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      discovery:
        ip: 192.168.2.110
        namespace: public
        username: ${spring.cloud.nacos.username}
        password: ${spring.cloud.nacos.password}
      config:
        server-addr: 127.0.0.1:8848
        group: DEFAULT_GROUP
        file-extension: yaml
        namespace: public
        username: ${spring.cloud.nacos.username}
        password: ${spring.cloud.nacos.password}
      username: nacos
      password: nacos
  config:
    import: optional:nacos:user-service.yaml
