spring:
  webflux:
    static-path-pattern: /_none_/**
  main:
    web-application-type: reactive
  application:
    name: gateway-service
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      discovery:
        # ip: 192.168.2.110
        namespace: public
        username: ${spring.cloud.nacos.username}
        password: ${spring.cloud.nacos.password}
      config:
        server-addr: 127.0.0.1:8848
        group: DEFAULT_GROUP
        file-extension: yaml
        namespace: public
        username: ${spring.cloud.nacos.username}
        password: ${spring.cloud.nacos.password}
      username: nacos
      password: nacos
    gateway:
      discovery:
        locator:
          enabled: false
  config:
    import: optional:nacos:${spring.application.name}.yaml



logging:
  level:
    reactor.netty.http.client: DEBUG
    org.springframework.cloud.loadbalancer: DEBUG
    org.springframework.web.reactive: DEBUG